name = input("Enter your name: ")
age = input("Enter your age: ")
gpa= input("Enter your gpa: ")
batch = input("Enter your batch: ")
print ("Student Information")
print("----------------------")
print("Name : " +name)
print("Age : "+age)
print("GPA : "+gpa)
print("Batch : "+batch)